# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'motion_detect_collect_data_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for motion_detect_collect_data_app
  pod 'IQKeyboardManagerSwift'



end
